//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleNameParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeopleNameParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARY
        ///PATRICIA
        ///LINDA
        ///BARBARA
        ///ELIZABETH
        ///JENNIFER
        ///MARIA
        ///SUSAN
        ///MARGARET
        ///DOROTHY
        ///LISA
        ///NANCY
        ///KAREN
        ///BETTY
        ///HELEN
        ///SANDRA
        ///DONNA
        ///CAROL
        ///RUTH
        ///SHARON
        ///MICHELLE
        ///LAURA
        ///SARAH
        ///KIMBERLY
        ///DEBORAH
        ///JESSICA
        ///SHIRLEY
        ///CYNTHIA
        ///ANGELA
        ///MELISSA
        ///BRENDA
        ///AMY
        ///ANNA
        ///REBECCA
        ///VIRGINIA
        ///KATHLEEN
        ///PAMELA
        ///MARTHA
        ///DEBRA
        ///AMANDA
        ///STEPHANIE
        ///CAROLYN
        ///CHRISTINE
        ///MARIE
        ///JANET
        ///CATHERINE
        ///FRANCES
        ///ANN
        ///JOYCE
        ///DIANE
        ///ALICE
        ///JULIE
        ///HEATHER
        ///TERESA
        ///DORIS
        ///GLORIA
        ///EVELYN
        ///JEAN
        ///CHERYL
        ///MILDRED
        ///KATHERINE
        ///JOAN
        ///ASHLEY
        ///JUDI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string female_names {
            get {
                return ResourceManager.GetString("female_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMES
        ///JOHN
        ///ROBERT
        ///MICHAEL
        ///WILLIAM
        ///DAVID
        ///RICHARD
        ///CHARLES
        ///JOSEPH
        ///THOMAS
        ///BASS
        ///CHRISTOPHER
        ///DANIEL
        ///PAUL
        ///MARK
        ///DONALD
        ///GEORGE
        ///KENNETH
        ///STEVEN
        ///EDWARD
        ///BRIAN
        ///RONALD
        ///ANTHONY
        ///KEVIN
        ///JASON
        ///MATTHEW
        ///GARY
        ///TIMOTHY
        ///JOSE
        ///LARRY
        ///JEFFREY
        ///FRANK
        ///SCOTT
        ///ERIC
        ///STEPHEN
        ///ANDREW
        ///RAYMOND
        ///GREGORY
        ///JOSHUA
        ///JERRY
        ///DENNIS
        ///WALTER
        ///PATRICK
        ///PETER
        ///HAROLD
        ///DOUGLAS
        ///HENRY
        ///CARL
        ///ARTHUR
        ///RYAN
        ///ROGER
        ///JOE
        ///JUAN
        ///JACK
        ///ALBERT
        ///JONATHAN
        ///JUSTIN
        ///TERRY
        ///GERALD
        ///KEITH
        ///SAMUEL
        ///WILLIE
        ///RALPH
        ///LAWRENCE
        ///NICHOLAS
        ///ROY
        ///BE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string male_names {
            get {
                return ResourceManager.GetString("male_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAN
        ///MS
        ///MISS
        ///MRS
        ///MR
        ///SR
        ///MASTER
        ///REV
        ///REVEREND
        ///FR
        ///FATHER
        ///DR
        ///DOCTOR
        ///ATTY
        ///ATTORNEY
        ///PROF
        ///PROFESSOR
        ///HON
        ///HONORABLE
        ///PRES
        ///PRESIDENT
        ///GOV
        ///GOVERNOR
        ///COACH
        ///OFC
        ///OFFICER
        ///MSGR
        ///REP
        ///REPRESENTATIVE
        ///SEN
        ///SENATOR
        ///ABM
        ///AMBASSADOR
        ///TREAS
        ///TREASURER
        ///SEC
        ///SECRETARY
        ///PVT
        ///PRIVATE
        ///CPL
        ///CORPORAL
        ///SGT
        ///SARGENT
        ///ADM
        ///ADMINISTRATIVE
        ///MAJ
        ///MAJOR
        ///CAPT
        ///CAPTAIN
        ///CMDR
        ///COMMANDER
        ///LT
        ///LIEUTENANT
        ///COL
        ///COLONEL
        ///GEN
        ///GENERAL
        ///JUDGE
        ///SISTER
        ///1SG
        ///1LT
        ///1ST
        ///1STLT
        ///2LT
        ///2NDLT
        ///AMB
        ///BG
        ///BGEN
        ///BRIGGEN
        ///BROTHER
        ///CDR
        ///CPT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefixes {
            get {
                return ResourceManager.GetString("prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVM
        ///CFRE
        ///CLU
        ///CPA
        ///CSC
        ///CSJ
        ///DC
        ///DD
        ///DDS
        ///DMD
        ///DO
        ///DVM
        ///EDD
        ///ESQ
        ///RSM
        ///I
        ///II
        ///III
        ///IV
        ///V
        ///VI
        ///VII
        ///IIX
        ///IX
        ///X
        ///INC
        ///JD
        ///JR
        ///LLD
        ///LTD
        ///MD
        ///OD
        ///OSB
        ///PC
        ///PE
        ///PHD
        ///PH
        ///RET
        ///RGS
        ///RN
        ///RNC
        ///SHCJ
        ///SJ
        ///SNJM
        ///SR
        ///SSMO
        ///USA
        ///USAF
        ///USAFR
        ///USAR
        ///USCG
        ///USMC
        ///USMCR
        ///USN
        ///USNR
        ///CFSP
        ///CHES
        ///ESQUIRE
        ///FACH
        ///RN
        ///MPH
        ///DED
        ///EDD
        ///MSPH
        ///MP
        ///DRPH
        ///MA
        ///MS
        ///BA
        ///BS
        ///MBA
        ///MSHSE
        ///CNLP
        ///FAPWCA
        ///SCSH
        ///LPC
        ///LLM
        ///FACC
        ///RPA
        ///FMA
        ///OP
        ///DPM
        ///CLU
        ///CHFC
        ///CFP
        ///CTF
        ///FAAP.
        /// </summary>
        internal static string suffixes {
            get {
                return ResourceManager.GetString("suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///JONES
        ///BROWN
        ///DAVIS
        ///MILLER
        ///WILSON
        ///MOORE
        ///TAYLOR
        ///ANDERSON
        ///THOMAS
        ///JACKSON
        ///WHITE
        ///HARRIS
        ///MARTIN
        ///THOMPSON
        ///GARCIA
        ///MARTINEZ
        ///ROBINSON
        ///CLARK
        ///RODRIGUEZ
        ///LEWIS
        ///LEE
        ///WALKER
        ///HALL
        ///ALLEN
        ///YOUNG
        ///HERNANDEZ
        ///KING
        ///WRIGHT
        ///LOPEZ
        ///HILL
        ///SCOTT
        ///GREEN
        ///ADAMS
        ///BAKER
        ///GONZALEZ
        ///NELSON
        ///CARTER
        ///MITCHELL
        ///PEREZ
        ///ROBERTS
        ///TURNER
        ///PHILLIPS
        ///CAMPBELL
        ///PARKER
        ///EVANS
        ///EDWARDS
        ///COLLINS
        ///STEWART
        ///SANCHEZ
        ///MORRIS
        ///ROGERS
        ///REED
        ///COOK
        ///MORGAN
        ///BELL
        ///MURPHY
        ///BAILEY
        ///RIVERA
        ///COOPER
        ///RICHARDSON
        ///COX
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surnames {
            get {
                return ResourceManager.GetString("surnames", resourceCulture);
            }
        }
    }
}
